/* ---------- PIPELINE — per-pipeline stage lists, shared by admin.html and client-login.html ---------- */
// Full names are the real stored values (portable, unambiguous); "short" is display-only for narrow columns.
const PIPELINE_STAGE_SETS = {
  'Purchase Pipeline': [
    {full:'Lead In', short:'In'},
    {full:'Discovery Call', short:'DCall'},
    {full:'App & Docs In', short:'DocsIn'},
    {full:'App & Docs Reviewed', short:'DocsOK'},
    {full:'Pre-Approval', short:'PA'},
    {full:'Accepted Offer', short:'OfferA'},
    {full:'Submitted', short:'Submitted'},
    {full:'Conditional Approval', short:'CApp'},
    {full:'Appraisal Ordered', short:'Appr.Pd'},
    {full:'Appraisal Approved', short:'Appr.OK'},
    {full:'Conditions Satisfied', short:'C.Sat'},
    {full:'Get Referrals and Reviews', short:'GetR'},
    {full:'Compliance', short:'Com'},
    {full:'Instructed', short:"Instr'd"},
    {full:'Instructions Received', short:'Instr.Rec'},
    {full:'Funded', short:'Funded'},
    {full:'Commission Paid', short:'Paid'},
    {full:'Compliance Paid', short:'CPaid'},
  ],
  'Refinance Pipeline': [
    {full:'Need In', short:'NeedIn'},
    {full:'Discovery Call', short:'DCall'},
    {full:'App & Docs In', short:'DocsIn'},
    {full:'App & Docs Reviewed', short:'DocsOK'},
    {full:'Submitted', short:'Submitted'},
    {full:'Conditional Approval', short:'CApp'},
    {full:'Appraisal Ordered', short:'Appr.Pd'},
    {full:'Appraisal Approved', short:'Appr.OK'},
    {full:'Conditions Satisfied', short:'C.Sat'},
    {full:'Get Referrals and Reviews', short:'GetR'},
    {full:'Compliance', short:'Com'},
    {full:'Instructed', short:"Instr'd"},
    {full:'Instructions Received', short:'Instr.Rec'},
    {full:'Funded', short:'Funded'},
    {full:'Commission Paid', short:'Paid'},
    {full:'Compliance Paid', short:'CPaid'},
  ],
  'Renewal Pipeline': [
    {full:'Lead In', short:'In'},
    {full:'Annual Review', short:'AnnRev'},
    {full:'12-Month Review', short:'12MoR'},
    {full:'6-Month Review', short:'6MoR'},
    {full:'4-Month Review', short:'4MoR'},
    {full:'Discovery Call', short:'DCall'},
    {full:'Application In', short:'AppIn'},
    {full:'Application & Docs Review', short:'DocsOK'},
    {full:'Submitted', short:'Submitted'},
    {full:'Conditional Approval', short:'CApp'},
    {full:'Appraisal Ordered', short:'Appr.Pd'},
    {full:'Appraisal Approved', short:'Appr.OK'},
    {full:'Conditions Satisfied', short:'C.Sat'},
    {full:'Compliance', short:'Com'},
    {full:'Instructed', short:"Instr'd"},
    {full:'Funded', short:'Funded'},
    {full:'Commission Paid', short:'Paid'},
    {full:'Compliance Paid', short:'CPaid'},
  ],
  'Reverse Mortgage Pipeline': [
    {full:'Lead In', short:'In'},
    {full:'Application In', short:'AppIn'},
    {full:'Referral Sent', short:'RefSent'},
    {full:'Referral Meeting Set', short:'RefMtg'},
    {full:'Submitted', short:'Submitted'},
    {full:'Approved', short:'Approved'},
    {full:'Compliance', short:'Com'},
    {full:'Instructions Sent', short:'Instr.Sent'},
    {full:'Instructions Received', short:'Instr.Rec'},
    {full:'Funded', short:'Funded'},
    {full:'Commission Paid', short:'Paid'},
    {full:'Compliance Made', short:'CMade'},
  ],
  'Foreclosures Pipeline': [
    {full:'Flyer Sent 1x', short:'Fly1'},
    {full:'Flyer Sent 2x', short:'Fly2'},
    {full:'Flyer Sent 3x', short:'Fly3'},
    {full:'Flyer Sent 4x', short:'Fly4'},
    {full:'Webinar Attended', short:'Webinar'},
    {full:'Called', short:'Called'},
    {full:'Wants Refi', short:'Refi'},
    {full:'Wants to Sell', short:'Sell'},
    {full:'Wants Refi + Sell', short:'Refi+Sell'},
  ],
  'Webinar Pipeline': [
    {full:'Registered', short:'Reg'},
    {full:'Watched Video', short:'Watched'},
    {full:'Called', short:'Called'},
    {full:'Interested', short:'Interested'},
    {full:'Not Interested', short:'NotInt'},
  ],
};
function getStagesForPipeline(pipelineName){
  return PIPELINE_STAGE_SETS[pipelineName] || PIPELINE_STAGE_SETS['Purchase Pipeline'];
}
